### ISSUE TITLE
Signs not working

### ISSUE THREAD

**Issue by nmek** [np98765/BattleKits#18]
I just updated to the newest version of battle kits(the one released yesterday) and signs arent working. The ones I already had on my map dont work and I cant make new ones.
my config is here
http://pastebin.com/tTfu3xQN
I have the configs in different files but put them all in one pastebin for conveince.
permissions:
http://pastebin.com/PCBiQEC6
Also when someone of the default rank dies they dont respawn with the pvp kit.

**Comment by nmek** [comment]
Forgot to list plugins and CB version
CB version is 1.4.5 build 2488 r0.2
Plugins (25): TimTheEnchanter, WorldBorder, NoMoreHunger, WorldEdit, NoCheatPlus, Buycraft, Vault, SimpleVanish, PermissionsEx, LogBlock, CombatTag, Paintball, WorldGuard, PotionCommands, iConomy, ReportRTS, PEXRank, Modifyworld, Votifier, AutoAnnouncer, KillsPay, Essentials, BattleKits, EssentialsSpawn, EssentialsChat

**Comment by lol768** [comment]
You need to enable signs and enable kits on respawn.

``` yaml
# Global BattleKits settings
# Add world-specific blocks by warapping everything in the name of the world.
# Restrictions are handled by permissions now.
settings:
  once-per-life: true
  auto-update: false
  enable-restrictions: true
  show-kit-info-on-respawn: false
  override-disable-respawn-kits: false #This disables kit respawning - keep it at false if you want to use them
instant-soup-drink:
  replenish-type: health
signs:
  enabled: true #This tells BattleKits to actually enable signs
  ignore-permissions: true
  ignore-costs: true
  ignore-world-restriction: true
  ignore-lives-restriction: false
indirect:
  ignore-costs: true
  ignore-permissions: true
  ignore-world-restriction: true
  ignore-lives-restriction: false
```
