### ISSUE TITLE
Killstreaks

### ISSUE THREAD

**Issue by np98765** [np98765/BattleKits#19]
I think that killstreaks would be a great addition to BattleKits (or even as a standalone plugin).  

Basically, every time a user kills another player, their kill-count is incremented by 1.  When they die, their kill-count is reset back to 0.  If the user reaches 'x' number of kills, a configurable message could be sent.  

One solution:
There could be a list of integers, and whenever the user's killstreak is changed, it would check with the list.  If the killstreaks matches a number on the list, it would broadcast a message.
    killcount: [5,10,20,50]
    '%player has killed %killcount enemies in a row!  Watch out!'

Alternatively, there could be a system where the user can define a message for each integer on the list.  For example, when a user reaches 5, 'Watch out!' could be the message, but when the user reaches 50, '%p is on fire!' would be displayed.  We could enhance this feature by allowing console commands to be run when the user reaches certain integers on the list, to give users a reward (i.e. Extra items, a special message, a new rank).

Questions, concerns, thoughts?

**Comment by lol768** [comment]
Yep, sound good. I'll stick the necessary config in the kitHistory file

**Comment by lol768** [comment]
Done. I've set it up like so:
global.yml

``` yaml
killStreaks:
  enabled: true
  actionDefault: 
    - '!&c<player> is on fire with <kills> kills>&c!'
    - '#&6Great job <player>!'
  action10: 
    - '!&c<player> has an amazing kill streak of &e<kills> kills&c!'
    - "#&eYou're so amazing you deserve to be opped!"
    - '/op <player>'
```

Note: this is just an example, not included in the actual default config :smiley:
