### ISSUE TITLE
Plugin Config.

### ISSUE THREAD

**Issue by Quinn13** [np98765/BattleKits#88]
Could you give a better explanation of the Global File as some things such as:
settings:
  once-per-life: false
  auto-update: false
  enable-restrictions: false
  show-kit-info-on-respawn: true
  override-disable-respawn-kits: false
  instant-soup-drink: false
  clear-default: false

**Comment by lol768** [comment]
Hi!
Certainly:

``` yaml
once-per-life: false #Whether kits can only be selected once-per-life or not
auto-update: false #Enables or disables the built-in auto-updater
enable-restrictions: false #Enable or disable permissions based restrictions (e.g. block c0ontrol etc)
show-kit-info-on-respawn: true #Show message saying user can get a new kit on respawn. Only applicable if once-per-life is on.
override-disable-respawn-kits: false #Completely disables permission based auto kit respawning if set to true
instant-soup-drink: false #Only right-click is required to drink soup, no need to hold down the mouse
clear-default: false #Whether or not to clear the inventory between kits. Only required if you're not defining every slot and you don't want kits to 'mix'
```
